services:

  fluent-bit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml
    ports:
      - "24224:24224"
    command: ["-c", "/fluent-bit/etc/fluent-bit.yaml"]
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  node-app:
    image: node-efk-app:1.1
    ports:
      - "10000:10000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"