Vagrant.configure("2") do |config|

  # Бокс Ubuntu
  config.vm.box = "ubuntu/jammy64"

  # Host name
  config.vm.hostname = "my-vm"

  # Local network
  config.vm.network "public_network"

  # Provisioning
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y nginx

    # Changing port 80 → 82
    sed -i 's/listen 80 default_server;/listen 82 default_server;/g' /etc/nginx/sites-available/default
    sed -i 's/listen \\[::\\]:80 default_server;/listen [::]:82 default_server;/g' /etc/nginx/sites-available/default

    systemctl restart nginx
  SHELL

  # Resource settings (RAM + CPU)
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrant-demo-vm"
    vb.memory = 1024
    vb.cpus = 2
  end

end

